# Generated by Django 4.1.1 on 2022-09-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
